// ===============================================================
// ⚠️  This file was auto-generated by CMake on 2025-12-30 15:54:42. Do NOT edit manually.
// ===============================================================

#pragma once

// Version injected by CMake (CI should set it). Defaults to 0.0.0 for dev builds.
#define LIVEKIT_BUILD_VERSION "0.0.0"
#define LIVEKIT_BUILD_FLAVOR "cpp"   

#ifdef DEBUG
#define LIVEKIT_BUILD_SUFFIX  "-debug"
#else
#define LIVEKIT_BUILD_SUFFIX  "-release"
#endif

// Follow params are auto generated by CMakeLists.txt
#define LIVEKIT_BUILD_DATE "2025-12-30 15:54:42" 
#define LIVEKIT_BUILD_COMMIT "56ee033"

#define LIVEKIT_BUILD_VERSION_FULL LIVEKIT_BUILD_VERSION LIVEKIT_BUILD_SUFFIX
